package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

// newGenDocsCmd is a hidden command that writes the CLI reference page for
// the documentation site from the live command tree, so the published flags
// can't drift from the code. CI runs it before building the docs.
func newGenDocsCmd() *cobra.Command {
	return &cobra.Command{
		Use:    "gen-docs <output.md>",
		Short:  "Write the CLI reference as Markdown",
		Hidden: true,
		Args:   cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			// A docs page in the source tree: the same modes as any other
			// checked-in file, so the docs build and other users can read it.
			if err := os.MkdirAll(filepath.Dir(args[0]), 0o755); err != nil { //nolint:gosec // G301: a directory in the source tree
				return err
			}
			return os.WriteFile(args[0], cliReference(cmd.Root()), 0o644) //nolint:gosec // G306: a docs page in the source tree
		},
	}
}

func cliReference(root *cobra.Command) []byte {
	var b bytes.Buffer
	b.WriteString("# CLI reference\n\n")
	b.WriteString("<!-- Generated by `contemper gen-docs`. Do not edit. -->\n\n")
	fmt.Fprintf(&b, "%s\n\n", root.Short)
	for _, c := range root.Commands() {
		if !c.IsAvailableCommand() || c.IsAdditionalHelpTopicCommand() {
			continue
		}
		fmt.Fprintf(&b, "## %s\n\n", c.CommandPath())
		fmt.Fprintf(&b, "%s\n\n", c.Short)
		if c.Long != "" {
			fmt.Fprintf(&b, "%s\n\n", c.Long)
		}
		fmt.Fprintf(&b, "```text\n%s\n```\n\n", c.UseLine())
		if flags := c.NonInheritedFlags().FlagUsages(); flags != "" {
			fmt.Fprintf(&b, "**Flags**\n\n```text\n%s```\n\n", flags)
		}
	}
	return []byte(strings.TrimRight(b.String(), "\n") + "\n")
}
